.TH "Test.cpp" 3 "Mon Dec 9 2019" "Doxygen Lab" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen Lab from the source code\&.
